server:
  port: 8888

spring:
  application:
    name: config-server
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  #  profiles:
  #    active: native
  cloud:
    config:
      server:
        #        native:
        #          search-locations: file://${user.home}/projects/playground/config/git-local-repo
        git:
          #          uri: file:///Users/kirok/projects/playground/config/git-local-repox
          uri: https://github.com/psick22/spring-cloud-config.git
#          username: <my-username>
#          password: <my-password>
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
